
== Preface

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.


[abstract]
== Abstract

Traditionally, geospatial communities used 2D coordinates and the vertical and temporal aspects were considered attributes rather than fully fledged coordinate systems. In an increasingly dynamic, speedier and multidimensional world, much confusion and lack of interoperability has occurred because of inconsistent approaches to time. Much effort has been expended by various international bodies to establish the Gregorian Calendar as a consistent timeline. This suffices for low precision, such as to the nearest minute, but not so when second or sub-second accuracy is required. For example, there has been differing practices and no consensus on whether leap seconds should be part of the Gregorian timeline.

The fundamental concepts of events, clocks, timescales, coordinates and calendars have been long established, but there is no clear, straightforward defining document. This document aims to to give clear consistent definitions of the fundamental concepts and terminology, so that people are well aware of the advantages and disadvantages of adopting a particular technological approach and then perhaps they can contribute to building better and more interoperable systems using other more detailed documents such as logical and implementation standards that have an agreed common conceptual basis and terminology.

This document is consistent with <<iso19111,ISO 19111>> and <<W3COWLTime>> in OWL.

The aim of this document is to establish clear concepts and terminology.

[.preface]
== Security Considerations

No security considerations have been made for this document.


[submitters]
== Submitters

All questions regarding this submission should be directed to the editor or the
submitters:

[%unnumbered]
|===
h| Name h| Affiliation

| Chris Little (editor) | U.K. Met Office
| Chuck Heazel | HeazelTech

|===

[.preface]
== Introduction

When OGC standards involve time, they generally refer to the ISO documents such as <<iso19108,ISO 19108>> (now largely superseded), <<iso19111,ISO 19111>>, <<iso8601,ISO 8601>>, and their freely available OGC equivalents, such as <<OGC_18-005r4>> (the equivalent to <<iso19111,ISO 19111>>).

Much effort over decades has gone into establishing complex structures to represent calendar based time, such as the <<iso8601,ISO 8601>> notation, and many date-time schemas. Because of this effort, many people use calendar based "coordinates", with the attendant ambiguities, imprecision and inappropriate scope.

The aim of this document is to establish clear concepts and terminology, so that people are well aware of the advantages and disadvantages of adopting a particular technological approach and then perhaps contribute to building better interoperable systems.
