== Attributes of the Regimes/Classes

The top level `Reference System` is an abstract super-class and does not have many attributes or properties. So far, only the total dimension of the reference system and the Location, Time or Domain of Applicability have been identified as essential.

The 'ReferenceSystem' has two abstract sub-classes: 'SpatialReferenceSystem' , which is defined in <<iso19111>>, and 'TemporalReferenceSystem', each with the attributes of Dimension and Domains of Applicability.

The Dimension is one for time, or a vertical reference system, but may be as much as 6 for spatial location with orientation.

Besides the conventional space and time, there may be other reference systems, such as wavelength/frequency, that can be addressed by the Abstract Conceptual Model.

=== Attributes of Events and Ordinal Temporal Reference Systems

. An OrdinalTemporal Reference System has a well-ordered finite sequence of events against which other events can b e compared.

. Name/Id

. Optional location, time or domain of applicability

. Optional Epoch, defined in some temporal reference system

. Listed or enumerated sequence of events with the first and last events

. Optional notations

[example]
Ancient annals of a country may give a sequence of emperors which could be used to 'date' another event such as "Emperor Xi built a canal", or may be used to date a particular reign. For example: "In the reign of Emperor Yi, a comet was sighted" and later research identifies this as an appearance of Hailey's Comet.

The events from the list may be instants, such as the change of reign, or intervals, such as the complete reign of each king.

Other documents may enable two such 'king lists' to be related, though not completely.

=== Attributes of simple Clock and Discrete Timescale

A clock is a regular, repeating, physical event, or 'tick', that can be counted. The sequence of tick counts is a timescale. The ticks may be grouped into a Unit of Meaure for convenience. Other events can be compared to the ticks on the timescale.

. Name/Id

. Optional location, time or domain of applicability

. Optional Epoch, defined in some temporal reference system

. Arithmetic: Integer

. Optional name for each tick

. Optional Start time or count

. Optional End time or count

. Optional Unit of Measure and number of ticks per Unit

. Optional notations

[example]
A well preserved fossilised log is recovered and the tree rings establish an annual 'tick'. The start and end times may be known accurately by comparison and matching with other known tree ring sequences, or perhaps only dated imprecisely via Carbon Dating, or its archaeological or geological context.

[example]
A clock is started, but undergoes a calibration process against some standards clock, so the initial, reliable Start Time does not start at Count Zero. The clock is accidentially knocked so that it is no longer correctly caliabrated, but is still working. the End Time is not the last time that the clock ticks.

=== Attributes of Clocks

. Name/Id

. Optional location, time or domain of applicability

. Optional Epoch, defined in some temporal reference system

. Tick definition

[example]
An atomic clock may be calibrated to be valid only for a given temperature range and altitude.

[example]
A pendulum clock may have each tick os swing of the pendulum adjusted to be an exace fraction or multiple of a second. The famous London "Big Ben" clock's pendulum is 4.4m long and ticks every two seconds.

=== Attributes of Timescales

. Name/Id

. Optional location, time or domain of applicability

. Optional Epoch, defined in some temporal reference system

. Arithmetic, whether counted integers or measured real/floating point numbers

. Optional Unit of Measure

[example]
TAI (International Atomic Time, Temps Atomique International) is coordinated by the BIPM (International Bureau of Weights and Measures, Bureau International de Poids et Measures) in Paris, France. It is based on the average of hundreds of separate atomic clocks around the world, all corrected to be at mean sea level and standard pressure and temperature. The epoch is defined by Julian Date 2443144.5003725 (1 January 1977 00:00:32.184).

[example]
The Julian Day is the continuous count of days (rotations of the Earth with respect to the Sun) since the beginning of the year 4173 BCE and will terminate at the end of the year 3267 CE. The count then starts again as "Period 2". Many computer based timescales, such as Unix Time, are based on the Julian DAy timescale, but with different epochs, to fit the numbers into the limited computer words.

=== Attributes of Units of Measure

The Direction attribute indicates whether counts or measures increase in the positive (future) or negative (past) direction. The attribute could be part of 'Timescale' of 'TemporalCoordinateReferenceSystem' rather than a separate class 'UnitOfMeasure', but on balace, it seems better here, as the names often imply directionality, such as fathoms increasing downwards, MYA (Millions of Years Ago) increasing earlier, Atmospheric Pressure in NPs (HectoPascals) decreasing upwards, and FL (FlightLevel) increasing upwards.

. Name/Id/Abbreviation

. Direction

[example]
The number of years before the Current Era (BCE, previously known as BC) increase further back in time, whereas the number of years in the Current Era (CE, previously known as AD) increase further into the future. Tis is an example of two timescales, adjacent but with no overlap. If there was a year zero defined, they could be replaced with one continuous timescale.

=== Attributes of a CRS and Continuous Timescales

Some clocks allow the measurement or intervals between ticks, such as the movement of the sun across the sky. Alternatively, the ticks may not be completely distinguishable, but are still stable enough over the time of applicability to allow measurements rather than counting to determine the passage of time.

. Name/Id

. Optional location, time or domain of applicability

. Optional Epoch, defined in some temporal reference system

. Arithmetic: Real/Floating point

. Optional name for the Unit of Measure

. Optional Start time or measure

. Optional End time of measure

. Optional notations

[example]
A long, deep ice core is retrieved from a stable ice-sheet. From long term meteorological observations, the rate of accumulation of ice is known, so linear length can be equated to time (assuming a stable climate too). This enable the dates of some previously unknown large scale volcanic eruptions to be identified and timed. Identifiable nuclear fallout from specific atmospheric atomic bomb tests increase the confidence in the timing accuracy.

[example]
A long, deep, sediment core is extracted from the bottom of a lake with a long geological history. Two layers in the core are dated using radiocarbon dating. Assuming steady rates of sediment deposition, a continuous timescale can be interpolated between the dated layers, and extrapolated before and after the dated layers.

=== Attributes of Calendars

Calendars combine different timescales and their clocks and unito of measure, and other events, to make a complex timeline against which events can be compared. Calculated algorithms are used to determine which instants of intervals on the compound timescale are identified and labeled.

. Name/id

. Optional location, time or domain of applicability

. Optional Epoch, defined in some temporal reference system

. Astronomical Type (e.g. solar, sidereal, lunar, luni-solar)

. Predictive type (e.g. observed or calculated)

. Optional Start time

. Optional End time

. Constituent units or clocks and counts or timescales

. Algorithms to link constituent timescales

. Optional notations

[example]
The modern Gregorian calendar is calculated solar calendar, with various epochs from 1588 CE through to 1922 CE depending on location or country.

The constituent timescales are days (earth's rotations), months (moon's orbit around the earth), years (earth's orbit around the sun) and seconds determined by atomic clocks. To accommodate discrepancies, leap days and leap seconds are intercalated in some years. The commonest notations for the Gregorian calendar are <<iso8601>> and its various restrictive profiles.

[example]
The modern Islamic calendar is an observed lunar calendar, and the major religious dates progress throughout the year, year on year. The important months are determined by the observation of new moons from Mecca.

[example]
The modern Jewish calendar is a calculated luni-solar calendar, and discrepancies in the solar year are addressed by adding 'leap months' every few years.

[example]
The Ba'hai calendar is a calculated solar calendar, but without any other astronomical aspects. The year consists of 19 months of 19 days each, with 4 or 5 intercalated days for a new year holiday.

[example]
The West African Yoruba traditional calendar is a solar calendar with months, but rather than subdividing a nominal month of 28 days into 4 weeks, 7 weeks of 4 days are used. This perhaps gave rise to the fortnightly (every 8 days) markets in many villages in the grasslands of north-west Cameroun.

[example]
Teams controlling remote vehicles on Mars use a solar calendar, with Martian years and martian days (called sols). Months are not used because there are two moons, with different, rather short, orbital periods.

