[appendix]
:appendix-caption: Annex
[[iso-glossary]]
== ISO Glossary

The following concepts from the ISO TC211 Harmonized UML model are referenced by the Temporal Conceptual UML model but do not play a major role in its' definition. They are provided here to support a more complete understanding of the model.

[[Area-section]]
*Area* +
The measure of the physical extent of any topologically 2-D geometric object. Usually measured in "square" units of length. +
{blank}[<<iso19103>>]

[[Boolean-section]]
*Boolean* +
Boolean is the mathematical datatype associated with two-valued logic +
{blank}[<<iso19103>>]

[[CC_CoordinateOperation-section]]
*CC_CoordinateOperation* +
A mathematical operation on coordinates that transforms or converts coordinates to another coordinate reference system. +
{blank}[<<iso19111>>]

[[Character-section]]
*Character* +
A symbol  from a standard character-set. +
{blank}[<<iso19103>>]

[[CharacterString-section]]
*CharacterString* +
Characterstring  is a family  of  datatypes which  represent strings of symbols  from  standard character-sets. +
{blank}[<<iso19103>>]

[[CRS2-section]]
*CRS* +
Coordinate reference system which is usually single but may be compound. +
{blank}[<<iso19111>>]

[[CV_DiscreteCoverage-section]]
*CV_DiscreteCoverage* +
A subclass of CV_Coverage that returns a single record of values for any direct position within a single geometric object in  its spatiotemporal domain. +
{blank}[<<iso19123>>]

[[CV_DomainObject-section]]
*CV_DomainObject* +
An element of the domain of the CV_Coverage. It is an aggregation of objects that may include any combination of GM_Objects (ISO 19107:2003), TM_GeometricPrimitives (ISO 10108), or spatial or temporal objects defined in other standards, such as the CV_GridPoint defined in this International Standard. +
{blank}[<<iso19123>>]

[[CV_GridPointValuePair-section]]
*CV_GridPointValuePair* +
A subtype of CV_GeometryValuePair that has a GM_GridPoint as the value of its geometry attribute. +
{blank}[<<iso19123>>]

[[CV_GridValuesMatrix-section]]
*CV_GridValuesMatrix* +
The geometry represented by the various offset vectors is in the image plane of the grid. +
{blank}[<<iso19123>>]

[[CV_ReferenceableGrid-section]]
*CV_ReferenceableGrid* +
A subclass of CV_Coverage that relates the grid coordinates to an external coordinate reference system. +
{blank}[<<iso19123>>]

[[Date-section]]
*Date* +
Date gives values for year, month and day. Representation of Date is specified in ISO 8601. Principles for date and time are further discussed in ISO 19108. +
{blank}[<<iso19103>>]

[[DateTime-section]]
*DateTime* +
A DateTime is a combination of a date and a time types. Representation of DateTime is specified in ISO 8601. Principles for date and time are further discussed in ISO 19108. +
{blank}[<<iso19103>>]

[[Distance-section]]
*Distance* +
Used as a type for returning distances and possibly lengths. +
{blank}[<<iso19103>>]

[[EngineeringCRS-section]]
*Engineering CRS* +
A contextually local coordinate reference system which can be divided into two broad categories:

. earth-fixed systems applied to engineering activities on or near the surface of the earth;
. CRSs on moving platforms such as road vehicles, vessels, aircraft or spacecraft. +
{blank}[<<iso19111>>]

[[GenericName-section]]
*Generic Name* +
Generic Name is the abstract class for all names in a NameSpace. Each instance of a GenericName is either a LocalName or a ScopedName. +
{blank}[<<iso19103>>]

[[Geometry-section]]
*Geometry* +
Geometry is the root class of the geometric object taxonomy and supports interfaces common to all geographically referenced geometric objects. + 
{blank}[<<iso19107>>]

[[GM_CompositePoint-section]]
*GM_CompositePoint* +
A GM_Complex containing one and only one GM_Point. +
{blank}[<<iso19107>>]

[[GM_CompositeSolid-section]]
*GM_CompositeSolid* +
A set of geometric solids adjoining one another along common boundary geometric surfaces +
{blank}[<<iso19107>>]

[[GM_GenericSurface-section]]
*GM_GenericSurface* +
GM_Surface and GM_SurfacePatch both represent sections of surface geometry, and therefore share a number of operation signatures. These are defined in the interface class GM_GenericSurface. +
{blank}[<<iso19107>>]

[[GM_LineString-section]]
*GM_LineString* +
Consists of sequence of line segments, each having a parameterization like the one for GM_LineSegment +
{blank}[<<iso19107>>]

[[GM_MultiPrimitive-section]]
*GM_MultiPrimitive* +
The root class for all primitive aggregates. The association role “element” shall be the set of GM_Primitives contained in this GM_MultiPrimitive. The attribute declaration here specializes the one at GM_Aggregate to include only GM_Primitives in this type of aggregate. +
{blank}[<<iso19107>>]

[[GM_OrientableSurface-section]]
*GM_OrientableSurface* +
A surface and an orientation inherited from GM_OrientablePrimitive. If the orientation is "+", then the GM_OrientableSurface is a GM_Surface. If the orientation is "-", then the GM_OrientableSurface is a reference to a GM_Surface with an upNormal that reverses the direction for this GM_OrientableSurface, the sense of "the top of the surface". +
{blank}[<<iso19107>>]

[[GM_PolyhedralSurface-section]]
*GM_PolyhedralSurface* +
A GM_Surface composed of polygon surfaces (GM_Polygon) connected along their common boundary curves. +
{blank}[<<iso19107>>]

[[GM_Position-section]]
*GM_Position* +
A union type consisting of either a DirectPosition or of a reference to a GM_Point from which a DirectPosition shall be obtained. +
{blank}[<<iso19107>>]

[[GM_Primitive-section]]
*GM_Primitive* +
The abstract root class of the geometric primitives. Its main purpose is to define the basic "boundary" operation that ties the primitives in each dimension together. +
{blank}[<<iso19107>>]

[[Integer-section]]
*Integer* +
An exact integer value, with no fractional part. +
{blank}[<<iso19103>>]

[[IoT_definition]]
*Internet of Things* +
The network of physical objects--“things”--that are embedded with sensors, software, and other technologies for the purpose of connecting and exchanging data with other devices and systems over the Internet. +  
{blank}https://en.wikipedia.org/wiki/Internet_of_things[Wikipedia]

[[IO_IdentifiedObjectBase-section]]
*IO_IdentifiedObjectBase* +
Supplementary identification and remarks information for a CRS or CRS-related object. +
{blank}[<<iso19111>>]

[[Length-section]]
*Length* +
The measure of distance as an integral, i.e. the limit of an infinite sum of distances between points on a curve. +
{blank}[<<iso19103>>]

[[Measure-section]]
*Measure* +
The result from performing the act or process of ascertaining the extent, dimensions, or quantity of some entity. +
{blank}[<<iso19103>>]

[[number-section]]
*Number* +
The base type for all number data, giving the basic algebraic operations. +
{blank}[<<iso19103>>]

[[Point-section]]
*Point* +
GM_Point is the basic data type for a geometric object consisting of one and only one point. +
{blank}[<<iso19107>>]

[[Real-section]]
*Real* +
The common binary Real finite implementation using base 2. +
{blank}[<<iso19103>>]

[[RS_ReferenceSystem-section]]
*RS_ReferenceSystem* +
Description of a spatial and temporal reference system used by a dataset. +
{blank}[<<iso19111>>]

[[ScopedName-section]]
*Scoped Name* +
ScopedName is a composite of a LocalName for locating another NameSpace and a GenericName valid in that NameSpace. ScopedName contains a LocalName as head and a GenericName, which might be a LocalName or a ScopedName, as tail. +
{blank}[<<iso19103>>]

[[Solid-section]]
*Solid* +
GM_Solid, a subclass of GM_Primitive, is the basis for 3-dimensional geometry. The extent of a solid is defined by the boundary surfaces. +
{blank}[<<iso19107>>]

[[Time-section]]
*Time* +
Time is the designation of an instant on a selected time scale, astronomical or atomic.  It is used in the sense of time of day. +
{blank}[<<iso19103>>]

[[TM_Duration-section]]
*TM_Duration* +
A data type to be used for describing length or distance in the temporal dimension. +
{blank}[<<iso19108>>]

[[TM_TemporalPosition-section]]
*TM_TemporalPosition* +
The position of a TM_Instant relative to a TM_ReferenceSystem. +
{blank}[<<iso19108>>]

[[UnitOfMeasure-section]]
*Unit of Measure* +
Any of the systems devised to measure some physical quantity such distance or area or a system devised to measure such things as the passage of time. +
{blank}[<<iso19103>>]

[[URI-section]]
*URI* +
Uniform Resource Identifier (URI), is a compact string of characters used to identify or name a resource +
{blank}[<<iso19103>>]

[[Volume-section]]
*Volume* +
Volume is the measure of the physical space of any 3-D geometric object. +
{blank}[<<iso19103>>]


