
== Preface

When OGC standards involve time, they generally refer to the ISO documents such as <<iso19108>> (now largely superseded), <<iso19111>>, <<iso8601>>, and their freely available OGC equivalents, such as <<ogc18005>> (the equivalent to <<iso19111>>).

Much effort over decades has gone into establishing complex structures to represent calendar based time, such as the <<iso8601>> notation, and many date-time schemas. Because of this effort, many people use calendar based "coordinates", with the attendant ambiguities, imprecision and inappropriate scope.

The aim of this Abstract Specification is to establish clear concepts and terminology, so that people are well aware of the advantages and disadvantages of adopting a particular technological approach and then perhaps contribute to building better interoperable systems.

[abstract]
== Abstract

Traditionally, geospatial communities used 2D coordinates and the vertical (third dimension) and temporal aspects were considered attributes rather than valid components of coordinate systems. In an increasingly dynamic, faster and multidimensional world, much confusion and lack of interoperability has occurred because of inconsistent approaches to defining and expressing time. Various international bodies expended considerable effort to establish the Gregorian Calendar as a consistent timeline. The Gregorian Calendar suffices for low precision applications, such as to the nearest minute, but not so when second or sub-second accuracy is required. For example, there has been differing practices and no consensus on whether leap seconds should be part of the Gregorian timeline.

The fundamental concepts of events, clocks, timescales, coordinates and calendars have been long established, but there is no clear, straightforward defining document. This Abstract Specification provides clear consistent definitions of the fundamental concepts and terminology.The conceptual model enables advantages and disadvantages of adopting a particular technological approach to be identified so that the community can contribute to building better and more interoperable systems by defining more detailed documents such as logical and implementation standards that have an agreed common conceptual basis and terminology.

This document is consistent with <<iso19111>> and <<w3cowltime,W3C Time Ontology>> in OWL.

The primary goal of the Abstract Conceptual Model for Time is to establish clear concepts and terminology.


[.preface]
== Security Considerations

This Abstract Specification does not place any constraints on application, platform, operating system level, or network security.


== Submitters

All questions regarding this submission should be directed to the editor or the
submitters:

[options="header"]
|===
| Name | Organization | Role

| Chris Little | U.K. Met Office | Editor
| Chuck Heazel | HeazelTech | Contributor
| Ronald Tse | Ribose Inc. | Contributor

|===

