
== Preface

When OGC Standards involve time, they generally refer to the ISO documents such as Geographic Information Temporal Schema <<iso19108>> (now largely superseded), Geographic information Referencing by coordinates <<iso19111>>, Date and Time Format <<iso8601>>, and the freely available OGC equivalents, such as OGC Abstract Specification Topic 2: Referencing by Coordinates  <<ogc18005>> (the equivalent to <<iso19111>>).

Over decades, much effort has gone into establishing complex structures to represent calendar based time, such as the <<iso8601>> notation, and many date-time schemas. A consequence of this effort is that many end-users and developers of software use calendar based "coordinates", with the associated ambiguities about underlying algorithms, imprecision and inappropriate scope.

The aim of this OGC Temporal Abstract Specification is to establish clear concepts and terminology. This is necessary so that people are aware of the advantages and disadvantages of specifying or adopting a particular technological approach to time and then perhaps build better, more appropriate, interoperable systems for their use cases.

[abstract]
== Abstract
[frame=none]
|===
|  “Quid est ergo tempus? |  |  |  | “What then is time?
|  Si nemo ex me quaerat, scio.|  |  |  | If no one asks me, I know. 
|  Si quaerenti explicare velim,|  |  |  | If I wish to explain to him who asks, 
|  nescio.”|  |  |  | I do not know.”
|          |  |  |  | _St. Augustine (354–430CE) Confessions, XI, 14_
|===



The primary goal of the Abstract Conceptual Model for Time is to establish clear concepts, their relationships, and terminology.

The fundamental concepts of events, clocks, timescales, coordinates and calendars have been long established, but there is no clear, straightforward defining document. This Abstract Specification provides clear consistent definitions of the fundamental concepts and terminology. The conceptual model enables advantages and disadvantages of adopting a particular technological approach to be identified and provides an opportunity for communities to build consistent, interoperable representations regardless of implementation.

Traditionally, geospatial communities used 2D coordinates and the vertical (third dimension) and temporal aspects were considered attributes rather than valid components of coordinate systems. In an increasingly dynamic, faster and multidimensional world, much confusion and lack of interoperability has occurred because of inconsistent approaches to defining and expressing time. Various international bodies expended considerable effort to establish the Gregorian Calendar as a consistent timeline. The Gregorian Calendar suffices for low precision applications, such as to the nearest minute, but not so when second or sub-second accuracy is required. For example, there have been differing practices and no consensus on whether leap seconds should be part of the Gregorian timeline.

This document is consistent with <<iso19111>> and <<w3cowltime,W3C Time Ontology>> in OWL.

[.preface]
== Security Considerations

This Abstract Specification does not place any constraints on application, platform, operating system level, or network security.


== Submitters

All questions regarding this submission should be directed to the editor or the
submitters:

[options="header"]
|===
| Name | Organization | Role

| Chris Little | U.K. Met Office | Editor
| Chuck Heazel | HeazelTech | Contributor
| Ronald Tse | Ribose Inc. | Contributor

|===

