== Conformance

Clause 7 of this Abstract Specification uses the Unified Modeling Language (UML) to present
conceptual schemas for describing the higher level classes of time and temporal reference systems. These schemas define conceptual classes that

. may be considered to comprise a cross-domain application schema, or

. may be used in application schemas, profiles and implementation specifications.

This flexibility is controlled by a set of UML types that can be implemented in a variety of manners. Use of
alternative names that are more familiar in a particular application is acceptable, provided that there is a one-
to-one mapping to classes and properties in this Abstract Specification.

The UML model in this Abstract Specification defines conceptual classes. Various software systems define
implementations or data structures. All of these reference the same information content. The same
name may be used in implementation classes as in the model, so that types defined in the UML model may be used
directly in application schemas.

Annex A defines a set of conformance tests that will support applications whose requirements range from the
minimum necessary to define data structures to full object implementation.
