
== Terms, definitions and abbreviated terms

=== Terms and definitions

==== clock

==== conceptual model

description of common concepts and their relationships, particularly in order to facilitate exchange of information between parties within a specific domain

NOTE: A conceptual model is explicitly chosen to be independent of design or implementation concerns.

==== coordinate

one of a sequence of numbers designating the position of a point

[.source]
<<iso19111>>

NOTE: In many coordinate reference systems, the coordinate numbers are qualified by units.

==== coordinate reference system
preferred:[CRS]

{{coordinate system}} that is related to an object by a {{datum}}

[.source]
<<iso19111>>

NOTE: Geodetic and vertical datums are referred to as reference frames.

NOTE: For geodetic and vertical reference frames, the object will be the Earth. In planetary applications, geodetic and vertical reference frames may be applied to other celestial bodies.

==== coordinate system

set of mathematical rules for specifying how coordinates are to be assigned to points

[.source]
<<iso19111>>


==== datum
admitted:[reference frame]

parameter or set of parameters that realize the position of the origin, the scale, and the orientation of a {{coordinate system}}

[.source]
<<iso19111>>


==== epoch
domain:[geodesy]

point in time

[.source]
<<iso19111>>

NOTE: In <<iso19111>>, an epoch is expressed in the Gregorian calendar as a decimal year.

[example]
2017-03-25 in the Gregorian calendar is epoch 2017.23. Other notations or reference systems are options.

==== reference frame
admitted:[datum]

parameter or set of parameters that realize the position of the origin, the scale, and the orientation of a {{coordinate system}}

[.source]
<<iso19111>>

==== temporal coordinate reference system
preferred:[TRS]

{{coordinate reference system}} based on a {{temporal datum}}

[.source]
<<iso19111>>

==== temporal coordinate system
domain:[geodesy]

one-dimensional {{coordinate system}} where the axis is time

[.source]
<<iso19111>>

==== temporal datum

{{datum}} describing the relationship of a {{temporal coordinate system}} to an object

[.source]
<<iso19111>>

NOTE: The object is normally time on the Earth.

==== tick

event which is a single occurrence of the repeating physical phenomenon of a clock

=== Abbreviations

2D:: 2-dimensional

3D:: 3-dimensional

BIPM:: International Bureau of Weights and Measures

TAI:: International Atomic Time

UML:: Unified Modeling Language
