== Classes and their Attributes and Properties

[[reference_system_section]]
=== Reference Systems

The top level `Reference System` class is an abstract super-class and does not have many attributes or properties. Only the total dimension of the reference system and the location, time or domain of applicability have been identified as essential.

The reference system class has two abstract sub-classes: `Spatial Reference System`, which is defined in <<iso19111>>, and `Temporal Reference System`, each with the inherited attributes of dimension and domains of applicability.

The value for dimension is one for time, or a vertical reference system, but may be as high as six for spatial location with orientation as in the <<OGCgeopose,GeoPose Implementation Standard>>.

Besides the conventional space and time, there may be other reference systems, such as wavelength or frequency, that could be addressed by future additions to this Abstract Conceptual Model.

[[ordinal_rs_section]]
=== Ordinal Temporal Reference Systems

An ordinal temporal reference system has a well-ordered finite sequence of events against which other events can be compared.

An ordinal temporal reference system is a type of temporal reference system. Therefore, it inherits the following attributes from the temporal reference system class:

. applicable location time or domain: the location, time or domain of applicability;
. dimension: the number of dimensions in this reference system. For ordinal temporal reference systems this value is fixed at 1.

An ordinal temporal reference system does not have any attributes of its own. However, it does use associations with other classes to fully describe itself.

. Epoch: An ordinal temporal reference system 'has a' one optional <<epoch_section,Epoch>>

. Notation: An ordinal temporal reference system 'can use' one or more <<notation_section,Notations>> to represent itself.

. Event: An ordinal temporal reference system 'consists of' an ordered set of <<events_section,Events>>. These events are identifiable temporal instances.

[example]
Ancient annals of a country may give a sequence of emperors which could be used to 'date' another event such as "Emperor Gaozu (Chinese: 漢高祖) built a canal", or may be used to date a particular reign. For example: "In the reign of Emperor Qin Shi Huang (Chinese: 秦始皇), a comet was sighted" and later research identifies this as an appearance of Halley's Comet.

[[events_section]]
==== Events

The events class is an ordered list of temporal events. The events can be instants, such as the ascension of a king to a throne, or intervals, such as the complete reign of each king.

Other documents may enable two such 'king lists' to be related, though usually not completely.

[[temporal_crs_section]]
=== Temporal Coordinate Reference Systems

A temporal coordinate reference system is a type of temporal reference system. Therefore, it inherits the following attributes from the temporal reference system class:

. applicable location time or domain: the location, time or domain of applicability;
. dimension: the number of dimensions in this reference system. For temporal coordinate reference systems this value is fixed at 1.

A temporal coordinate reference system does not have any attributes of its own. However, it does use associations with other classes to fully describe itself.

. Epoch: A temporal coordinate reference system 'has a' one optional <<epoch_section,Epochs>>

. Notation: A temporal coordinate reference system 'can use' one or more <<notation_section,Notations>> to represent itself.

. Timescale: A temporal coordinate reference system 'has a' one <<timescale_section,Timescale>> which is used to represent the values along its single axis. This timescale can be either discrete or continuous.

[[calendar_section]]
=== Calendar Reference Systems

Calendars combine different timescales and their clocks and units of measure, and other events, to make a complex timeline against which events can be compared. Calculated algorithms are used to determine which instants or intervals on the compound timeline are identified and labeled.

A calendar is a type of temporal reference system. Therefore, it inherits the following attributes from the temporal reference system class:

. applicable location time or domain: the location, time or domain of applicability
. dimension: the number of dimensions in this reference system. For calendars this value is fixed at 1.

A calendar does not have any attributes of its own. However, it does use associations with other classes to fully describe itself.

. Algorithm: A calendar 'has a' one or more <<algorithm_section,Algorithms>>. These algorithms specify how the multiple timescales are aggregated into a single <<timeline_section,Timeline>>.
. Epoch: A calendar 'has a' one optional <<epoch_section,Epoch>>
. Notation: A calendar 'can use' one or more <<notation_section,Notations>> to represent itself.
. Timeline: A calendar 'has a' one <<timeline_section,Timeline>> which serves to aggregate a number of <<timescale_section,Timescales>> into a single coherent measure of date and time.
. Timescale: A calendar 'has a' two or more <<timescale_section,Timescales>> which are used to construct a <<timeline_section,Timeline>>.

[[timeline_section]]
==== Timeline

The timeline is usually a set of instants from the past to the future and is compounded from multiple timescales, with multiple units of measures, and complicated arithmetic determined by the calendar algorithm(s). The timeline is usually not even continuous, having gaps or even multiple simultaneous representations.

A timeline does not have any attributes of its own. Nor does it inherit any attributes from a parent class. However, it does use associations with other classes to fully describe itself.

. Algorithm: A timeline 'has a' one or more <<algorithm_section,Algorithms>>. These algorithms specify how the multiple timescales are aggregated into a single timeline.
. Timescale: A timeline 'has a' two or more <<timescale_section,Timescales>> which are used to construct the timeline.

[[algorithm_section]]
==== Algorithm

An algorithm specifies the logic used to construct a timeline from its constituent <<timescale_section,Timescales>>. An algorithm does not have any attributes of its own. Nor does it make use of any other classes from this temporal abstract conceptual model.

==== Calendar Examples

[example]
The modern Gregorian calendar is a calculated solar calendar, with various epochs from 1588 CE through to 1922 CE depending on location or country.

The constituent timescales are days (earth's rotations), months (moon's orbit around the earth), years (earth's orbit around the sun) and seconds determined by atomic clocks. To accommodate discrepancies, leap days and leap seconds are intercalated in some years. The commonest notations for the Gregorian calendar are <<iso8601>> and its various restrictive profiles.

[example]
The timeline in a country may have gaps when clocks 'spring forward' for enacting daylight-saving time. There may not be any time corresponding to the times between 01:00 and 02:00. When the daylight-saving time is revoked, and clocks 'fall back', the times between 01:00 and 02:00 occur twice.

[example]
The modern Islamic calendar is an observed lunar calendar, and the major religious dates progress throughout the year, year on year. The important months are determined by the observation of new moons from Mecca.

[example]
The modern Jewish calendar is a calculated lunisolar calendar, and discrepancies from the solar year are addressed by adding 'leap months' every few years.

[example]
The Ba'hai calendar is a calculated solar calendar, but without any other astronomical aspects. The year consists of 19 months of 19 days each, with 4 or 5 intercalated days for a new year holiday.

[example]
The West African Yoruba traditional calendar is a solar calendar with months, but rather than subdividing a nominal month of 28 days into 4 weeks, 7 weeks of 4 days are used. This perhaps gave rise to the fortnightly (every 8 days) markets in many villages in the grasslands of north-west Cameroon.

[example]
Teams controlling remote vehicles on Mars use a solar calendar, with Martian years and Martian days (called sols). Months are not used because there are two moons, with different, rather short, orbital periods.

[example]
The <<ifc,International Fixed Calendar>> was a solar calendar with 13 months of 28 days, with an extra day at the year's end after the thirteenth month and leap days inserted at the end of the sixth month. Months all started on the same day of the week, Sunday, and ended on a Saturday. The year-end day and leap days are not part of any week. The IFC was considered for global introduction by the League of Nations but finally rejected in 1937, though it formed the basis for some financial accounting systems for many years. 

=== Discrete and Continuous Time Scales

A <<clock_section,clock>> may be a regular, repeating, physical event, or tick, that can be counted. The sequence of tick counts form a discrete (counted) <<timescale_section,timescale>>.

Some <<clock_section,clocks>>  allow the measurement of intervals between ticks, such as the movement of the sun across the sky. Alternatively, the ticks may not be completely distinguishable, but are still stable enough over the time of applicability to allow measurements rather than counting to determine the passage of time. These clocks generate a continuous (measured) <<timescale_section,timescale>>.

The duration of a tick is a constant. The duration of a tick is specified using a <<unitsOfMeasure_section,Unit Of Measure>>.

[[timescale_section]]
==== Timescale

A timescale is a linear measurement (one dimension) used to measure or count monotonic events. Timescale has three attributes:

. Arithmetic: an indicator of whether this timescale contains counted integers or measured real/floating point numbers.
. StartCount: the lowest value in a timescale. The data type of this attribute is specified by the 'arithmetic' attribute.
. EndCount: the greatest value in a timescale. The data type of this attribute is specified by the 'arithmetic' attribute.

In addition to the attributes, the timescale class maintains associations with two other classes to complete its definition.

. Clock: A timescale 'has a' one <<clock_section,clock>>. This is the process which generates the tick which is counted or measured for the timescale.
. UnitOfMeasure: A timescale 'has a' one <<unitsOfMeasure_section,UnitOfMeasure>>. This class specifies the units of the clock measurement as well as the direction of increase of that measurement.

[[clock_section]]
==== Clock

A clock represents the process which generates the tick which is counted or measured for a timescale. Clock has one attribute:

. Tick definition: a description of the process which is being used to generate monotonic events.

[example]
An atomic clock may be calibrated to be valid only for a given temperature range and altitude.

[example]
A pendulum clock may have each tick or swing of the pendulum adjusted to be an exact fraction or multiple of a second. The famous London "Big Ben" clock's pendulum is 4.4 m long and ticks every two seconds.

[[unitsOfMeasure_section]]
==== Unit of Measure

The direction attribute indicates whether counts or measures increase in the positive (future) or negative (past) direction. The attribute could be part of timescale or temporal coordinate reference system rather than a separate class of measure, but on balance, it seems better here, as the names often imply directionality, such as fathoms increasing downwards, MYA (Millions of Years Ago) increasing earlier, atmospheric pressure in hPa (hectopascals) decreasing upwards, and FL (flight level) increasing upwards.

. Direction: indicates the direction in which a timescale progresses as new ticks are counted or measured.

[example]
The number of the years before the Current Era (BCE, previously known as BC) increase further back in time, whereas the number of the years in the Current Era (CE, previously known as AD) increase further into the future. This is an example of two timescales, adjacent but with no overlap. If there was a year zero defined, they could be replaced with one continuous timescale.

==== Time Scale Examples

[example]
A long, deep ice core is retrieved from an ice sheet. From chemical identification of layers representing known large scale volcanic eruptions, the connection between depth and time is known, so length can be converted to time. This enables the dates of some previously unknown large scale volcanic eruptions to be identified and timed.

[example]
A long, deep, sediment core is extracted from the bottom of a lake with a long geological history. Two layers in the core are dated using radiocarbon dating. Assuming steady rates of sediment deposition, a continuous timescale can be interpolated between the dated layers, and extrapolated before and after the dated layers.

[example]
A well preserved fossilized log is recovered and the tree rings establish an annual 'tick'. The start and end times may be known accurately by comparison and matching with other known tree ring sequences, or perhaps only dated imprecisely via Carbon Dating, or its archaeological or geological context.

[example]
A clock is started, but undergoes a calibration process against some standard clock, so the initial, reliable start time does not start at a count of zero. The clock is accidentally knocked so that it is no longer correctly calibrated, but is still working. The end time is not the last time that the clock ticks.

[example]
TAI (International Atomic Time, Temps Atomique International) is coordinated by the <<bipm_define,BIPM>> (International Bureau of Weights and Measures, Bureau International de Poids et Measures) in Paris, France. TAI is based on the average of hundreds of separate atomic clocks around the world, all corrected to be at mean sea level and standard pressure and temperature. The epoch is defined by Julian Date 2443144.5003725 (1 January 1977 00:00:32.184).

[example]
The Julian Day is the continuous count of days (rotations of the Earth with respect to the Sun) since the beginning of the year 4173 BCE and will terminate at the end of the year 3267 CE. The count then starts again as "Period 2". Many computer based timescales, such as <<unix_time,Unix Time>>, are based on the Julian Day timescale, but with different epochs, to fit the numbers into the computer words of limited size.

=== Supporting Classes

[[epoch_section]]
==== Epoch

The epoch class provides a origin or datum for a temporal reference system.

[[notation_section]]
==== Notation

The notation class identifies a widely agreed, commonly accepted, notation for representing values in accordance with a temporal reference system.
