== Temporal Geometry

The geospatial community has often used analogies between space and time to construct 'temporal-geometry'. This analogy is useful but can be misleading and must not be taken too far. For example, taken from <<treatise,A Treatise on Time and Space by J R Lucas>>, and assuming a `thing` has classical rather than quantum properties:

1.1 A thing cannot be in two places at one time;

1.2 A thing can be in one place at two times;

2.1 Two things cannot be in the same place at the same time;

2.2 Two things can be in the same place at different times.

These statements are not symmetrical between space and time.

Temporal constructs such as instants, durations or intervals, multi-instants (a set of instants), and multi-intervals are not included in this conceptual model. These do have strongly analogous equivalents in space, such as points and multi-points, especially in a single dimension, such as vertical. The temporal constructs are well described in <<temporal_knowledge,Maintaining Knowledge about Temporal Intervals by J. F. Allen>> (see <<fig-interval-relations>>) and apply across all of the regimes, so do not need to be in this Abstract Conceptual Model.
