
.Preface

<Insert Preface text here.>

[NOTE]
====
Give OGC specific commentary: describe the technical content, reason for document, history of the document and precursors, and plans for future work.

There are two ways to specify the Preface: "simple clause" or "full clasuse"

If the Preface does not contain subclauses, it is considered a simple preface clause. This one is entered as text after the `.Preface` label and must be placed between the AsciiDoc document attributes and the first AsciiDoc section title. It should not be give a section title of its own.

If the Preface contains subclauses, it needs to be encoded as a full preface clause. This one is recognized as a full Metanorma AsciiDoc section with te title "Preface", i.e. `== Preface`. (Simple preface content can also be encoded like full preface.)
====


[abstract]
== Abstract

Traditionally, geospatial communities used 2D coordinates and the vertical and temporal aspects were considered attributes rather than fully fledged coordinate systems. In an increasingly dynamic, speedier and multidimensional world, much confusion and lack of interoperability has occurred because of inconsistent approaches to time. Much effort has been expended by various international bodies to establish the Gregorian Calendar as a consistent timeline. This suffices for low precision, of say minutes, but not so when second or sub-second accuracy is required. Also, there has also been iffereing practice and no consensus on whether leap seconds should be part of the Gregorian timeline.

The fundamental concepts of events, clocks, timescales, coordinates and calendars have been long established, but there is no clear, straightfoward  defining document. This Abstract Topic specification aims to to give clear consistent definitions of the fundamental concepts, so that other, more detailed standard documents such as logical and implementation standards have an agreed conceptual basis, thus improving interoperability.

This document is consistent with ISO 19111:2019 Geographic information — Referencing by Coordinates and W3C Time Ontology in OWL.

[.preface]
== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

[%unnumbered]
|===
h| Name h| Affiliation
| Chris Little | Met Office
| Charles Heazel | Heazel 
...
|===


[.preface]
== Introduction

<Insert introduction here.>


[.preface]
== Reference notes

<Place reference notes here.>


[NOTE]
====
If you need to place any further sections in the preface area
use the `[.preface]` attribute.
====
