
.Preface
Attention is drawn to the possibility that some of the elements of this document may be the
subject of patent rights. The Open Geospatial Consortium shall not be held responsible for
identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any
relevant patent claims or other intellectual property rights of which they may be aware that
might be infringed by any implementation of the standard set forth in this document, and to
provide supporting documentatio

[abstract]
== Abstract

Traditionally, geospatial communities used 2D coordinates and the vertical and temporal aspects were considered attributes rather than fully fledged coordinate systems. In an increasingly dynamic, speedier and multidimensional world, much confusion and lack of interoperability has occurred because of inconsistent approaches to time. Much effort has been expended by various international bodies to establish the Gregorian Calendar as a consistent timeline. This suffices for low precision, for example of one minute, but not so when second or sub-second accuracy is required. Also, there has been differing practice and no consensus on whether leap seconds should be part of the Gregorian timeline.

The fundamental concepts of events, clocks, timescales, coordinates and calendars have been long established, but there is no clear, straightfoward  defining document. This document aims to to give clear consistent definitions of the fundamental concepts and terminology, so that people are well aware of the advantages and disadvantages of adopting a particular technological approach and then perhaps they can contribute to building better and more interoperable systems sing other more detailed documents such as logical and implementation standards that have an agreed common conceptual basis and terminology.

This document is consistent with ISO 19111:2019 Geographic information — Referencing by Coordinates and W3C Time Ontology in OWL.

The aim of this document is to establish clear concepts and terminology.

[.preface]
== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

[%unnumbered]
|===
h| Name h| Affiliation
| Chris Little | Met Office
| Chuck Heazel | HeazelTech
...
|===

[.preface]
== Introduction
When OGC standards involve time, they generally refer to the ISO documents such as ISO 19108 (now obsolete), ISO 19111, ISO8601, and their freely available OGC equivalents, such as Abstract Specification Topic 2 Referencing by Coordinates (equivalent to ISO 19111).

Much effort over decades has gone into establishing complex structures to represent calendar based time, such as the ISO8601 notation, and many date-time schemas. Because of this effort, many people use calendar based "coordinates", with the attendant ambiguities, imprecision and inappropriate scope.

The aim of this document is to establish clear concepts and terminology, so that people are well aware of the advantages and disadvantages of adopting a particular technological approach and then perhaps contribute to building better interoperable systems.

[.preface]
== Reference notes

<Place reference notes here.>
