
[appendix]
== Bibliography

* [[[ogc22-036,OGC 22-036]]], OGC: OGC 22-036: TESTBED-18: 3D+ STANDARDS FRAMEWORK ENGINEERING REPORT (DRAFT) http://www.opengis.net/doc/PER/T18

•  22-038r2 Testbed-18: Reference Frame Transformation Engineering Report

* [[[iso19107,ISO 19107:2003]]], ISO 19107:2003 Geographic information — Spatial schema, 2003 https://www.iso.org/standard/26012.html

* [[[iso19108, ISO 19108:2002]]], ISO 19108:2002 Geographic information — Temporal schema, 2002 https://www.iso.org/standard/26013.html

* [[[iso19111, ISO 19111:2019]]], ISO 19111:2019 Geographic information — Referencing by coordinates, 2019, https://www.iso.
org/standard/74039.html

* [[[ogcGeoPose, OGC GeoPose]]], OGC: GeoPose Specification draft, 2021. https://github.com/opengeospatial/GeoPose/

SO: Geographic information — Reference model — Part 1: Fundamentals, 2014. https://www.
iso.org/standard/59164.html

ISO: Geographic information — Conceptual schema language, 2015. https://www.iso.org/
standard/56734.html

ISO: Geographic information — Spatial referencing by geographic identifiers, 2019. https://
www.iso.org/standard/70742.html

ISO: Geographic information — Well-known text representation of coordinate reference
systems, 2019. https://www.iso.org/standard/76496.html

ISO: Geographic information — Geography Markup Language (GML), 2007. https://www.iso.
org/standard/32554.html

Adrian Custer: OGC 09-083r4, GeoAPI 3.0 Implementation Standard with corrigendum. Open
Geospatial Consortium (2018). https://portal.ogc.org/files/?artifact id=71648.

[3] OGC: OGC 22-038: Reference Frame Transformation Engineering Report, 2022. http://
ogc.pages.ogc.org/T18-3Dplus_Data_Standards_and_Streaming/documents/D025/
document.html

[4] Astronomical Algorithms, Jean Meeus, https://www.agopax.it/Libri_astronomia/pdf/
Astronomical%20Algorithms.pdf

[5] Consultative Committee for Space Data Systems, NAVIGATION DATA—DEFINITIONS
AND CONVENTIONS,2019, https://public.ccsds.org/Pubs/500x0g4.pdf

[6] Springer Handbook of Global Navigation Satellite Systems, Peter J.G. Teunissen, Oliver
Montenbruck, https://doi.org/10.1007/978-3-319-42928-1

[7] IERS Earth rotation data — https://www.iers.org/IERS/EN/DataProducts/
EarthOrientationData/eop.html

[8] NASA NAIF, SPICE Documentation, retrieved January 2023, https://naif.jpl.nasa.gov/
naif/tutorials.html

[9] The Open Group, UNIX Time, retrieved January 2023, https://pubs.opengroup.org/
onlinepubs/9699919799/basedefs/V1_chap04.html#tag_04_16

[10] Calendrical Calculations - The Ultimate Eidtion, Nachum Dershowitz, Edward M. Reingold. Paperback: 618
pages. Cambridge University Press; 4th edition (2018) Language: English. ISBN-13: 978-1107683167.

[11] http://emr.cs.iit.edu/home/reingold/calendar-book/third-edition

[12] Allen, J. F., 'Maintaining Knowledge about Temporal Intervals', Communications of
the ACM, 1983, vol. 26 pp. 832-843.

[13] ISO 8601:2004, Data elements and interchange formats - Information interchange -
Representation of dates and times.

[14] Theory of Modelling and Simulation: Integrating Discrete Event and Continuous Complex Dynamic Systems: Second Edition by B. P. Zeigler, H. Praehofer, T. G. Kim, Academic Press, San Diego, CA, 2000.
 
[15] A Brief Hsitory of Timekeeping, Chad Orzell. Paperback: 324 pages. Oneworld Publications; 1st edtion (2022) Language English. ISBM-13: 978-0-86154-321-2.

Universal Coordinated Time (UTC),

Bureau International des Poids et Mesures (BIPM)

International Earth Rotation and Reference Systems Service (IERS)
